spring:
  datasource:
    username: datnguyen
    password: 28102004
    url: jdbc:postgresql://localhost:5432/yourtutor
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug